version: '3'

services:
  backend:
    build: ./backend
    command: /start_prod.sh
    volumes:
      - .:/code
      - django-static:/backend/static
      - media_volume:/usr/src/app/mediafiles
    networks:
      - django-nginx
      - backend_network
    expose:
      - 8000
    depends_on:
      - db
    links:
      - db:db
    environment: 
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}

  db:
    image: postgres
    restart: always
    networks:
      - django-nginx
      - backend_network

  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - 1337:80
    networks:
      - django-nginx
    volumes:
      - ./nginx/prod.conf:/etc/nginx/nginx.conf:ro
      - django-static:/usr/src/app/static
      - media_volume:/usr/src/app/mediafiles
    depends_on:
      - backend

volumes:
  django-static:
  media_volume:

networks:
  django-nginx:
    driver: bridge
  backend_network:
    driver: bridge
