version: '3'

services:
  backend:
    build: ./backend
    command: /start_prod.sh
    volumes:
      - .:/code
      - ./backend/static:/usr/src/app/static
      - ./backend/media/:/usr/src/app/media
    networks:
      - django-nginx
    expose:
      - 8000
    depends_on:
      - db
    links:
      - db:db
    environment: 
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}

  db:
    image: postgres
    restart: always
    networks:
      - django-nginx

  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - "80:80"
    networks:
      - django-nginx
    volumes:
      - ./nginx/prod.conf:/etc/nginx/nginx.conf:ro
      - ./backend/static:/usr/src/app/static
      - ./backend/media/:/usr/src/app/media
    depends_on:
      - backend

networks:
  django-nginx:
    driver: bridge
