version: '3'

services:
  backend:
    build: ./backend
    command: /start_prod.sh
    volumes:
      - .:/code
      - django-static:/backend/static
    networks:
      - django-nginx
      - backend_network
    depends_on:
      - db
    links:
      - db:db
      

  db:
    image: postgres
    restart: always
    networks:
      - django-nginx
      - backend_network

  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - 80:80
    networks:
      - django-nginx
    volumes:
      - ./nginx/prod.conf:/etc/nginx/nginx.conf:ro
      - django-static:/usr/src/app/static
    depends_on:
      - backend
      - backend_network

volumes:
  django-static:

networks:
  django-nginx:
    driver: bridge
  backend_network:
    driver: bridge
