# Generated by Django 2.2.3 on 2019-07-21 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('technology', models.CharField(max_length=20)),
                ('github_link', models.URLField(blank=True, max_length=250, null=True)),
                ('sample_doc', models.FileField(blank=True, null=True, upload_to='docs/%Y-%m-%D/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='covers/%Y-%m-%D/')),
            ],
        ),
    ]
