# Generated by Django 2.2.3 on 2019-08-02 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('description', models.TextField()),
                ('github_link', models.URLField(blank=True, max_length=250, null=True)),
                ('linkedIn_link', models.URLField(blank=True, max_length=250, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('resume', models.FileField(blank=True, null=True, upload_to='docs/')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('technology', models.CharField(max_length=20)),
                ('github_link', models.URLField(blank=True, max_length=250, null=True)),
                ('sample_doc', models.FileField(blank=True, null=True, upload_to='docs/')),
                ('project_img', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
