# Generated by Django 2.2.3 on 2019-08-03 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_author_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='sample_doc',
        ),
        migrations.AlterField(
            model_name='project',
            name='project_img',
            field=models.ImageField(default='images/test1.gif', unique=True, upload_to='images/'),
        ),
    ]
