# Generated by Django 2.2.3 on 2019-08-03 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20190803_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='sample_doc',
            field=models.FileField(blank=True, null=True, upload_to='docs/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
